// Generated by CoffeeScript 1.9.3
(function() {
  var Nex, isBlank,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Nex = this.Nex || require('nex');

  isBlank = Spine.isBlank;

  Nex.Contact = (function(superClass) {
    extend(Contact, superClass);

    Contact.prototype.className = 'contact';

    Contact.prototype.events = {
      'tap .send': 'send',
      'keyup': 'onkeyup'
    };

    Contact.prototype.elements = {
      'form': 'form'
    };

    Contact.prototype.defaults = {
      dataType: 'json',
      processData: false,
      headers: {
        'X-Requested-With': 'XMLHttpRequest'
      }
    };

    Contact.prototype.logPrefix = '(App) NexContact: ';

    function Contact() {
      this.onKeyup = bind(this.onKeyup, this);
      this.send = bind(this.send, this);
      this.getxsrf = bind(this.getxsrf, this);
      Contact.__super__.constructor.apply(this, arguments);
      this.defaultFields = ['message', 'subscribe'];
    }

    Contact.prototype.onkeyup = function(e) {
      return this.validate(e.target);
    };

    Contact.prototype.onchange = function(e) {
      this.log('onchange');
      return this.validate(e.target);
    };

    Contact.prototype.validate = function(el) {
      var field;
      field = $(el).closest('.field');
      if (el.checkValidity()) {
        return field.removeClass('error');
      } else {
        return field.addClass('error');
      }
    };

    Contact.prototype.getxsrf = function(xhr, settings) {
      return $.ajax({
        type: 'GET',
        async: false,
        url: Nex.data === 'online' && Nex.debug ? "http://" + Nex.tenant + ".imagoapp.com/api/v2/getxsrf" : "/api/v2/getxsrf"
      }).success(function(data) {
        return xhr.setRequestHeader("Nex-Xsrf", data);
      }).error((function(_this) {
        return function() {
          return _this.el.addClass('error');
        };
      })(this));
    };

    Contact.prototype.formToJson = function(form) {
      var array, elem, i, len, message, obj, ref;
      array = $(form).serializeArray();
      obj = {};
      message = '';
      for (i = 0, len = array.length; i < len; i++) {
        elem = array[i];
        if (ref = elem.name, indexOf.call(this.defaultFields, ref) < 0) {
          message += (Nex.Utils.titleCase(elem.name)) + ": " + elem.value + "<br><br>";
        }
        obj[elem.name] = elem.value || (elem.value = '');
      }
      obj.message = message + Nex.Utils.replaceNewLines(obj.message || '');
      return JSON.stringify(obj);
    };

    Contact.prototype.send = function(e) {
      var field, i, len, ref, settings;
      e.preventDefault();
      ref = $('input,textarea,select');
      for (i = 0, len = ref.length; i < len; i++) {
        field = ref[i];
        this.validate(field);
      }
      if (!this.form[0].checkValidity()) {
        return;
      }
      settings = {
        beforeSend: this.getxsrf,
        data: this.formToJson(this.form),
        url: Nex.data === 'online' && Nex.debug ? "http://" + Nex.tenant + ".imagoapp.com/api/v2/contact" : "/api/v2/contact",
        method: 'POST'
      };
      settings = $.extend({}, this.defaults, settings);
      return $.ajax(settings).success((function(_this) {
        return function(e) {
          return _this.el.addClass('success');
        };
      })(this)).error((function(_this) {
        return function(e) {
          return _this.log("error with form", e);
        };
      })(this));
    };

    Contact.prototype.onKeyup = function(e) {
      var key;
      if (!this.isActive()) {
        return;
      }
      key = Nex.Utils.getKeyName(e);
      if (typeof this[key] === 'function') {
        return this[key]();
      }
    };

    return Contact;

  })(Spine.Controller);

  module.exports = Nex.Contact;

}).call(this);
