// Generated by CoffeeScript 1.7.1
(function() {
  var Nex, isBlank,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Nex = this.Nex || require('nex');

  isBlank = Spine.isBlank;

  Nex.Contact = (function(_super) {
    __extends(Contact, _super);

    Contact.prototype.className = 'contact';

    Contact.prototype.events = {
      'tap .send': 'send',
      'keyup': 'onkeyup'
    };

    Contact.prototype.elements = {
      'form': 'form'
    };

    Contact.prototype.defaults = {
      dataType: 'json',
      processData: false,
      headers: {
        'X-Requested-With': 'XMLHttpRequest'
      }
    };

    Contact.prototype.logPrefix = '(App) Contact: ';

    function Contact() {
      this.onKeyup = __bind(this.onKeyup, this);
      this.send = __bind(this.send, this);
      this.getxsrf = __bind(this.getxsrf, this);
      Contact.__super__.constructor.apply(this, arguments);
    }

    Contact.prototype.onkeyup = function(e) {
      return this.validate(e.target);
    };

    Contact.prototype.validate = function(el) {
      var field;
      field = $(el).parent();
      if (el.checkValidity()) {
        return field.removeClass('error');
      } else {
        return field.addClass('error');
      }
    };

    Contact.prototype.getxsrf = function(xhr, settings) {
      return $.ajax({
        type: 'GET',
        async: false,
        url: Nex.data === 'online' && Nex.debug ? "http://" + Nex.tenant + ".imagoapp.com/api/v2/getxsrf" : "/api/v2/getxsrf"
      }).success(function(data) {
        return xhr.setRequestHeader("Nex-Xsrf", data);
      }).error((function(_this) {
        return function() {
          return _this.el.addClass('error');
        };
      })(this));
    };

    Contact.prototype.formToJson = function(form) {
      var array, elem, obj, _i, _len;
      array = $(form).serializeArray();
      obj = {};
      for (_i = 0, _len = array.length; _i < _len; _i++) {
        elem = array[_i];
        obj[elem.name] = elem.value || (elem.value = '');
      }
      return JSON.stringify(obj);
    };

    Contact.prototype.send = function(e) {
      var field, settings, _i, _len, _ref;
      e.preventDefault();
      _ref = $('input,textarea');
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        field = _ref[_i];
        this.validate(field);
      }
      if (!this.form[0].checkValidity()) {
        return;
      }
      settings = {
        beforeSend: this.getxsrf,
        data: this.formToJson(this.form),
        url: Nex.data === 'online' && Nex.debug ? "http://" + Nex.tenant + ".imagoapp.com/api/v2/contact" : "/api/v2/contact",
        method: 'POST'
      };
      settings = $.extend({}, this.defaults, settings);
      return $.ajax(settings).success((function(_this) {
        return function(e) {
          return _this.el.addClass('success');
        };
      })(this)).error(function(e) {
        return console.log("error with form", e);
      });
    };

    Contact.prototype.onKeyup = function(e) {
      var key;
      if (!this.isActive()) {
        return;
      }
      key = Nex.Utils.getKeyName(e);
      if (typeof this[key] === 'function') {
        return this[key]();
      }
    };

    return Contact;

  })(Spine.Controller);

  module.exports = Nex.Contact;

}).call(this);

//# sourceMappingURL=contact.map
