// Generated by CoffeeScript 1.6.3
(function() {
  var Gallery,
    _this = this;

  Gallery = {
    next: function() {
      if (!(_this.cur < (_this.manager.controllers.length - 1))) {
        return;
      }
      _this.cur++;
      return _this.manager.controllers[_this.cur].active();
    },
    prev: function() {
      if (!(_this.cur > 0)) {
        return;
      }
      _this.cur--;
      return _this.manager.controllers[_this.cur].active();
    }
  };

  module.exports = Gallery;

}).call(this);

/*
//@ sourceMappingURL=gallery.map
*/
