// Generated by CoffeeScript 1.7.1
(function() {
  var Asset, CartItem, Collection, Generic, Image, Member, Proxy, Search, Setting, Video,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Search = require("./search");

  Asset = (function(_super) {
    __extends(Asset, _super);

    function Asset() {
      return Asset.__super__.constructor.apply(this, arguments);
    }

    Asset.configure('Asset');

    Asset.extend(Search);

    Asset.id_to_kind = function(id) {
      var kind;
      if (id.indexOf('Collection-') === 0) {
        kind = 'Collection';
      } else if (id.indexOf('Generic-') === 0) {
        kind = 'Generic';
      } else if (id.indexOf('Proxy-') === 0) {
        kind = 'Proxy';
      } else if (id.indexOf('Order-') === 0) {
        kind = 'Order';
      } else if (id.match(/[0-9a-z]{8}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{12}/)) {
        kind = 'Image';
      } else if (id.match(/[0-9a-z]{56}/)) {
        kind = 'Video';
      }
      return kind;
    };

    Asset.globalFind = function(id) {
      return this.get_model(id).find(id);
    };

    Asset.globalExists = function(id) {
      return this.get_model(id).exists(id);
    };

    Asset.get_model = function(id_or_kind) {
      return Nex.Models[id_or_kind] || Nex.Models[this.id_to_kind(id_or_kind)];
    };

    Asset.create_or_update = function(attrs, options) {
      var model;
      model = this.get_model(attrs.id);
      if (!model.exists(attrs.id)) {
        return model.create(attrs, options);
      }
      return model.update(attrs.id, attrs, options);
    };

    Asset.related = function(params) {
      params.context = params.context.id ? params.context.id : params.context;
      params.limit || (params.limit = 10);
      params.related = typeof context.getMeta === "function" ? context.getMeta(params.propname, []) : void 0;
      return this.get(params);
    };

    Asset.prototype.related = function(params) {
      params.context = this;
      return Asset.related(params);
    };

    Asset.prototype.getMeta = function(field, fallback) {
      var original_value, value, _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7;
      if (fallback == null) {
        fallback = '';
      }
      if (!field) {
        return fallback;
      }
      if ((_ref = this.meta[field]) != null ? (_ref1 = _ref.value) != null ? _ref1.hasOwnProperty('value') : void 0 : void 0) {
        value = (_ref2 = this.meta[field]) != null ? _ref2.value.value : void 0;
      } else {
        value = (_ref3 = this.meta[field]) != null ? _ref3.value : void 0;
      }
      if ((_ref4 = this.meta[field]) != null ? (_ref5 = _ref4.original_value) != null ? _ref5.hasOwnProperty('value') : void 0 : void 0) {
        original_value = (_ref6 = this.meta[field]) != null ? _ref6.original_value.value : void 0;
      } else {
        original_value = (_ref7 = this.meta[field]) != null ? _ref7.original_value : void 0;
      }
      return value || original_value || fallback;
    };

    Asset.prototype.options = function() {
      var key, obj, opts, variant, _i, _len, _ref, _ref1, _ref2;
      opts = {};
      _ref = this.variants;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        variant = _ref[_i];
        _ref1 = variant.meta;
        for (key in _ref1) {
          obj = _ref1[key];
          key = Nex.Utils.pluralize(key);
          opts[key] || (opts[key] = []);
          if (_ref2 = obj.value, __indexOf.call(opts[key], _ref2) < 0) {
            opts[key].push(obj.value);
          }
        }
      }
      return opts;
    };

    Asset.prototype.discounted = function() {
      return this.variants[0].meta.discounted && ((this.variants[0].meta.discounted.value > 0) || (this.variants[0].meta.discounted.value[Nex.currency] > 0));
    };

    Asset.prototype.upvote = function() {
      var host, successResponse, _base;
      (_base = this.meta).liked || (_base.liked = {
        value: 0
      });
      this.meta.liked.value++;
      this.save();
      successResponse = (function(_this) {
        return function(data, status, xhr, options) {
          return console.log('liked +1', _this.meta.liked.value);
        };
      })(this);
      host = Nex.data === 'online' && Nex.debug ? "http://" + Nex.tenant : "";
      return $.ajax({
        contentType: 'application/json',
        dataType: 'json',
        processData: false,
        headers: Spine.Ajax.defaults,
        data: JSON.stringify({
          'liked': {
            'value': this.meta.liked.value
          }
        }),
        type: 'PUT',
        url: host + '/api/v2/metaupdate/' + this.id
      }).success(successResponse).error(function() {
        return deferred.resolve();
      });
    };

    return Asset;

  })(Spine.Model);

  Collection = (function(_super) {
    __extends(Collection, _super);

    function Collection() {
      return Collection.__super__.constructor.apply(this, arguments);
    }

    Collection.configure('Collection', 'kind', 'name', 'meta', 'path', 'serving_url', 'variants', 'date_created', 'date_modified', 'resolution', 'sort_by', 'sort_order', 'assets', 'hidden', 'normname', 'canonical');

    return Collection;

  })(Asset);

  Image = (function(_super) {
    __extends(Image, _super);

    function Image() {
      return Image.__super__.constructor.apply(this, arguments);
    }

    Image.configure('Image', 'kind', 'name', 'meta', 'path', 'serving_url', 'variants', 'date_created', 'date_modified', 'resolution', 'filesize', 'normname', 'canonical');

    return Image;

  })(Asset);

  Video = (function(_super) {
    __extends(Video, _super);

    function Video() {
      return Video.__super__.constructor.apply(this, arguments);
    }

    Video.configure('Video', 'kind', 'name', 'meta', 'path', 'serving_url', 'variants', 'date_created', 'date_modified', 'resolution', 'filesize', 'normname', 'canonical', 'formats');

    return Video;

  })(Asset);

  Generic = (function(_super) {
    __extends(Generic, _super);

    function Generic() {
      return Generic.__super__.constructor.apply(this, arguments);
    }

    Generic.configure('Generic', 'kind', 'name', 'meta', 'serving_url', 'path', 'date_created', 'date_modified', 'resolution', 'normname', 'canonical', 'variants');

    return Generic;

  })(Asset);

  Proxy = (function(_super) {
    __extends(Proxy, _super);

    function Proxy() {
      return Proxy.__super__.constructor.apply(this, arguments);
    }

    Proxy.configure('Proxy', 'kind', 'name', 'meta', 'path', 'serving_url', 'variants', 'date_created', 'date_modified', 'resolution', 'filesize', 'normname', 'proxypath', 'thumb');

    return Proxy;

  })(Asset);

  Setting = (function(_super) {
    __extends(Setting, _super);

    function Setting() {
      return Setting.__super__.constructor.apply(this, arguments);
    }

    Setting.configure('Setting', 'label', 'name', 'value', 'section', 'order', 'type', 'visible', 'width', 'options');

    Setting.findAllBySection = function(section) {
      var settings;
      settings = this.findAllByAttribute('section', section);
      settings.sort(function(a, b) {
        return a.order - b.order;
      });
      return settings;
    };

    Setting.extend(Spine.Model.Ajax);

    return Setting;

  })(Spine.Model);

  Member = (function(_super) {
    __extends(Member, _super);

    function Member() {
      return Member.__super__.constructor.apply(this, arguments);
    }

    Member.configure('Member', 'email', 'first_name', 'last_name');

    Member.getMember = function() {
      var deferred, promise, successResponse;
      deferred = $.Deferred();
      promise = deferred.promise();
      successResponse = (function(_this) {
        return function(data, status, xhr, options) {
          var member;
          member = data.email ? _this.create(data) : void 0;
          return deferred.resolve(member);
        };
      })(this);
      $.ajax({
        contentType: 'application/json',
        dataType: 'json',
        processData: false,
        headers: Spine.Ajax.defaults,
        type: 'GET',
        url: '/api/v2/member'
      }).success(successResponse).error(function() {
        return deferred.resolve();
      });
      return promise;
    };

    Member.login = function() {
      return this._axaxCall('POST', {
        action: 'loginurl'
      });
    };

    Member.logout = function() {
      return this._axaxCall('POST', {
        action: 'logouturl'
      });
    };

    Member.checkout = function() {
      return this._axaxCall('POST', {
        action: 'checkout'
      });
    };

    Member._axaxCall = function(type, data) {
      var deferred, promise;
      deferred = $.Deferred();
      promise = deferred.promise();
      $.ajax({
        contentType: 'application/json',
        dataType: 'json',
        processData: false,
        headers: Spine.Ajax.defaults,
        type: type,
        data: JSON.stringify(data),
        url: '/api/v2/member'
      }).success(function(data, status, xhr, options) {
        if (data.url) {
          return window.location = data.url;
        } else {
          return deferred.resolve(data);
        }
      }).error(function() {
        return console.log('error');
      });
      return promise;
    };

    return Member;

  })(Spine.Model);

  CartItem = (function(_super) {
    __extends(CartItem, _super);

    function CartItem() {
      return CartItem.__super__.constructor.apply(this, arguments);
    }

    CartItem.configure('CartItem', 'meta', 'serving_url', 'quantity', 'price', 'color', 'size', 'itemid', 'headline', 'description');

    CartItem.addToCart = function(itemid, quantity, options) {
      var existing, item;
      if (options == null) {
        options = {
          'size': '',
          'color': '',
          headline: '',
          description: ''
        };
      }
      existing = this.select(function(item) {
        return item.itemid === itemid;
      });
      if (existing.length) {
        item = existing[0];
        item.quantity = item.quantity + quantity;
        item.save();
        return;
      }
      item = {
        itemid: itemid,
        quantity: quantity,
        color: options != null ? options.color : void 0,
        size: options != null ? options.size : void 0,
        serving_url: options != null ? options.serving_url : void 0,
        price: options != null ? options.price : void 0,
        headline: options != null ? options.headline : void 0,
        description: options != null ? options.description : void 0
      };
      return this.create(item);
    };

    CartItem.extend(Spine.Model.Ajax);

    return CartItem;

  })(Spine.Model);

  Spine.Ajax.defaults.headers['NexClient'] = Nex.client;

  Nex.Models = {
    Collection: Collection,
    Asset: Asset,
    Image: Image,
    Video: Video,
    Proxy: Proxy,
    Setting: Setting,
    Generic: Generic,
    Member: Member,
    CartItem: CartItem
  };

  module.exports = Nex.Models;

}).call(this);

//# sourceMappingURL=models.map
