// Generated by CoffeeScript 1.7.1
(function() {
  var Nex;

  Nex = this.Nex = {};

  Nex.Widgets = Nex.Widgets || {};

  Nex.debug = window.location.host.indexOf(':') > 0;

  Nex.data = 'online';

  Nex.client || (Nex.client = 'public');

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Nex;
  }

}).call(this);
