// Generated by CoffeeScript 1.6.3
(function() {
  var Nex;

  Nex = this.Nex = {};

  Nex.dev = window.location.host.indexOf(':') > 0;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Nex;
  }

}).call(this);
