// Generated by CoffeeScript 1.7.1
(function() {
  var Nex,
    __slice = [].slice;

  Nex = this.Nex = {};

  Nex.Widgets = Nex.Widgets || {};

  Nex.debug = window.location.host.indexOf(':') > 0;

  Nex.data = 'online';

  Nex.client || (Nex.client = 'public');

  Nex.log = {
    logPrefix: '(Nex.log) ',
    log: function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (!Nex.debug) {
        return;
      }
      if (this.logPrefix) {
        args.unshift(this.logPrefix);
      }
      if (typeof console !== "undefined" && console !== null) {
        if (typeof console.log === "function") {
          console.log.apply(console, args);
        }
      }
      return this;
    }
  };

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Nex;
  }

}).call(this);
