// Generated by CoffeeScript 1.7.1
(function() {
  var Nex,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Nex = this.Nex || require('nex');

  Nex.Utils || (Nex.Utils = require('./utils'));

  Nex.Page = (function(_super) {
    __extends(Page, _super);

    Page.include(Nex.Panel);

    Page.prototype.className = 'page';

    Page.prototype.logPrefix = "(App) Page: ";

    function Page() {
      this.onKeyup = __bind(this.onKeyup, this);
      Page.__super__.constructor.apply(this, arguments);
      this.controllers = [];
      this.bind('ready', this.render);
      this.active(this.getData);
    }

    Page.prototype.tmpl404 = function() {
      return "<h1 class='" + Nex.language + "'>Page not Found</h1>";
    };

    Page.prototype.render = function(result) {
      var _ref;
      if (!((_ref = result.items) != null ? _ref.length : void 0)) {
        return this.html(this.tmpl404());
      }
    };

    Page.prototype.add = function(controller) {
      this.controllers.push(controller);
      return this.append(controller);
    };

    Page.prototype.replaceWithWidget = function(wrapper, controller) {
      this.log('wrapper, controller', wrapper, controller.el || controller);
      this.controllers.push(controller);
      return wrapper.replaceWith(controller.el || controller);
    };

    Page.prototype.activate = function() {
      $('body').on('keyup.page', this.onKeyup);
      $('body').addClass(this.className);
      return Page.__super__.activate.apply(this, arguments);
    };

    Page.prototype.deactivate = function() {
      $('body').off('.page');
      $('body').removeClass(this.className);
      this.clear();
      return Page.__super__.deactivate.apply(this, arguments);
    };

    Page.prototype.clear = function() {
      var cont, _i, _len, _ref;
      _ref = this.controllers;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        cont = _ref[_i];
        cont.release();
      }
      this.controllers = [];
      return this.html('');
    };

    Page.prototype.onKeyup = function(e) {
      var key;
      if (!this.isActive()) {
        return;
      }
      key = Nex.Utils.getKeyName(e);
      if (typeof this[key] === 'function') {
        return this[key]();
      }
    };

    return Page;

  })(Spine.Controller);

  module.exports = Nex.Page;

}).call(this);
