// Generated by CoffeeScript 1.6.3
(function() {
  var Nex,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Nex = this.Nex || require('nex');

  Nex.Page = (function(_super) {
    __extends(Page, _super);

    Page.include(Nex.Panel);

    Page.prototype.className = 'page';

    Page.prototype.logPrefix = "(App) Page: ";

    function Page() {
      Page.__super__.constructor.apply(this, arguments);
      this.tmpl404 = '<h1>Page not Found</h1>';
      this.controllers = [];
      this.bind('ready', this.render);
      this.active(this.getData);
    }

    Page.prototype.render = function(result) {
      var _ref;
      if (!((_ref = result.items) != null ? _ref.length : void 0)) {
        return this.html(this.tmpl404({
          language: Nex.language
        }));
      }
    };

    Page.prototype.add = function(controller) {
      this.controllers.push(controller);
      return this.append(controller);
    };

    Page.prototype.deactivate = function() {
      this.clear();
      return Page.__super__.deactivate.apply(this, arguments);
    };

    Page.prototype.clear = function() {
      var cont, _i, _len, _ref;
      _ref = this.controllers;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        cont = _ref[_i];
        cont.release();
      }
      return this.controllers = [];
    };

    return Page;

  })(Spine.Controller);

  module.exports = Nex.Page;

}).call(this);

/*
//@ sourceMappingURL=page.map
*/
