// Generated by CoffeeScript 1.7.0
(function() {
  var Nex,
    __slice = [].slice;

  Nex = this.Nex || require('nex');

  Nex.Panel = {
    getData: function(query) {
      if (!query) {
        return this.log("Panel: query is empty, aborting " + query);
      }
      if (typeof query === 'string') {
        query = {
          path: query
        };
      }
      this.query = query;
      return Nex.Models.Asset.get(query, false).done((function(_this) {
        return function() {
          return _this.trigger.apply(_this, ['ready'].concat(__slice.call(arguments)));
        };
      })(this)).fail((function(_this) {
        return function() {
          return _this.log("Panel: Could not get data for panel " + _this.query);
        };
      })(this));
    },
    setTitle: function(result) {
      var title;
      title = Nex.Models.Setting.findByAttribute('name', 'title');
      return $('title').text("" + (result.headline || 'Imago') + " - " + title.value);
    }
  };

  module.exports = Nex.Panel;

}).call(this);

//# sourceMappingURL=panel.map
