// Generated by CoffeeScript 1.6.3
(function() {
  var Nex,
    __slice = [].slice;

  Nex = this.Nex || require('nex');

  Nex.Panel = {
    getData: function(path) {
      var _this = this;
      if (!path) {
        return this.log("Panel: path is empty, aborting " + path);
      }
      this.path = path;
      if (Nex.debug) {
        console.log('(Nex.Panel) path: ', path);
      }
      return Nex.Models.Asset.get({
        path: path
      }).done(function() {
        if (Nex.debug) {
          _this.log.apply(_this, ['(Nex.Panel) result: '].concat(__slice.call(arguments)));
        }
        return _this.trigger.apply(_this, ['ready'].concat(__slice.call(arguments)));
      }).fail(function() {
        return _this.log("Panel: Could not get data for panel " + path);
      });
    },
    setTitle: function(result) {
      var title;
      title = Nex.Models.Setting.findByAttribute('name', 'title');
      return $('title').text("" + (result.headline || 'Imago') + " - " + title.value);
    }
  };

  module.exports = Nex.Panel;

}).call(this);

/*
//@ sourceMappingURL=panel.map
*/
