// Generated by CoffeeScript 1.6.3
(function() {
  var Nex;

  Nex = this.Nex || require('nex');

  Nex.Search = {
    get: function(params, abortable) {
      var deferred, getAssetsDone, getAssetsFail, getCollectionDone, getCollectionFail, getSearchDone, getSearchFail, promise, result,
        _this = this;
      if (abortable === void 0 && Nex.client === 'public') {
        abortable = true;
      }
      if (abortable && this.jqXHR) {
        this.jqXHR.abort('abort');
      }
      params = this.objListToDict(params);
      deferred = $.Deferred();
      promise = deferred.promise();
      result = {
        items: [],
        count: 0
      };
      getAssetsDone = function(assets) {
        if (result.kind === 'Collection') {
          result.items = _this.sortassets(result.assets, assets);
          result.count = assets.length;
        }
        return deferred.resolve(result);
      };
      getAssetsFail = function() {
        return deferred.reject();
      };
      getCollectionDone = function(collection) {
        if (!collection) {
          return deferred.resolve(result);
        }
        result = collection;
        return _this.getAssets(collection, params).done(getAssetsDone).fail(getAssetsFail);
      };
      getCollectionFail = function() {
        return deferred.reject();
      };
      getSearchDone = function(data, status, xhr) {
        var assets;
        assets = _this.parseData(data);
        result.items = assets;
        result.count = assets.length;
        return deferred.resolve(result);
      };
      getSearchFail = function(xhr, statusText, error) {
        return deferred.reject(arguments);
      };
      if (params.path) {
        this.getCollection(params).done(getCollectionDone).fail(getCollectionFail);
      } else {
        this.getSearch(params).done(getSearchDone).fail(getSearchFail);
      }
      return promise;
    },
    getSearch: function(params) {
      var _this = this;
      this.jqXHR = $.ajax({
        contentType: 'application/json',
        dataType: 'json',
        processData: false,
        headers: {
          'X-Requested-With': 'XMLHttpRequest',
          'NexClient': Nex.client
        },
        type: 'POST',
        data: JSON.stringify(params),
        url: this.getSearchUrl()
      }).always(function() {
        return _this.jqXHR = null;
      });
      return this.jqXHR;
    },
    getCollection: function(params) {
      var Collection, collection, colparams, deferred, path, promise,
        _this = this;
      deferred = $.Deferred();
      promise = deferred.promise();
      path = params.path[0];
      Collection = this.get_model('Collection');
      collection = Collection.findByAttribute('path', path);
      if (collection) {
        return deferred.resolve(collection);
      } else {
        colparams = {
          'path': params.path
        };
        this.getSearch(colparams).done(function(data, status, xhr) {
          delete params.path;
          collection = _this.parseData(data)[0];
          return deferred.resolve(collection);
        });
      }
      return promise;
    },
    getAssets: function(collection, params) {
      var assets, deferred, id, promise, toFetch,
        _this = this;
      deferred = $.Deferred();
      promise = deferred.promise();
      delete params.path;
      if (collection.kind === 'Collection') {
        toFetch = collection.assets;
        assets = [];
        if (!Object.keys(params).length) {
          toFetch = (function() {
            var _i, _len, _ref, _results;
            _ref = collection.assets;
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              id = _ref[_i];
              if (!this.globalExists(id)) {
                _results.push(id);
              }
            }
            return _results;
          }).call(this);
          assets = (function() {
            var _i, _len, _ref, _results;
            _ref = collection.assets;
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              id = _ref[_i];
              if (this.globalExists(id)) {
                _results.push(this.globalFind(id));
              }
            }
            return _results;
          }).call(this);
        }
        if (!toFetch.length) {
          return deferred.resolve(assets);
        }
        params.ids = toFetch;
        params.ancestor = collection.id;
        this.getSearch(params).done(function(data, status, xhr) {
          assets = assets.concat(_this.parseData(data));
          return deferred.resolve(assets);
        });
      } else {
        deferred.resolve([]);
      }
      return promise;
    },
    sortassets: function(ids, assets) {
      var asset, i, id, orderedlist, _i, _j, _len, _len1;
      orderedlist = [];
      for (_i = 0, _len = ids.length; _i < _len; _i++) {
        id = ids[_i];
        for (i = _j = 0, _len1 = assets.length; _j < _len1; i = ++_j) {
          asset = assets[i];
          if (asset.id === id) {
            orderedlist.push(asset);
            break;
          }
        }
      }
      return orderedlist;
    },
    parseData: function(data) {
      var asset, obj, objs, _i, _len;
      objs = [];
      if (typeof data === 'string') {
        data = JSON.parse(data);
      }
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        obj = data[_i];
        asset = this.create_or_update(obj, {
          ajax: false
        });
        objs.push(asset);
      }
      return objs;
    },
    objListToDict: function(obj_or_list) {
      var elem, key, querydict, value, _i, _len;
      querydict = {};
      if (Spine.isArray(obj_or_list)) {
        for (_i = 0, _len = obj_or_list.length; _i < _len; _i++) {
          elem = obj_or_list[_i];
          for (key in elem) {
            value = elem[key];
            querydict[key] || (querydict[key] = []);
            querydict[key].push(value);
          }
        }
      } else {
        for (key in obj_or_list) {
          value = obj_or_list[key];
          querydict[key] = Spine.isArray(value) ? value : [value];
        }
      }
      if (querydict.collection != null) {
        querydict['path'] = querydict.collection;
        delete querydict.collection;
      }
      return querydict;
    },
    getSearchUrl: function() {
      if (Nex.client === 'public') {
        if (Nex.data === 'online') {
          return "http://" + Nex.tenant + ".imagoapp.com/api/v2/search";
        } else {
          return "/api/v2/search";
        }
      } else {
        return "/api/v2/search";
      }
    }
  };

  module.exports = Nex.Search;

}).call(this);

/*
//@ sourceMappingURL=search.map
*/
