// Generated by CoffeeScript 1.7.1
(function() {
  var Nex,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Nex = this.Nex || require('nex');

  Nex.Search = {
    get: function(params, abortable, fetchAssets, ajax) {
      var deferred, getAssetsDone, getAssetsFail, getCollectionDone, getCollectionFail, getLocalSearchDone, getLocalSearchFail, getSearchDone, getSearchFail, promise, result, _ref;
      this.abortable = abortable;
      if (fetchAssets == null) {
        fetchAssets = true;
      }
      if (ajax == null) {
        ajax = true;
      }
      if (this.abortable === void 0 && Nex.client === 'public') {
        this.abortable = true;
      }
      if ((_ref = this.jqXHR) != null) {
        _ref.abort('abort');
      }
      params = this.objListToDict(params);
      deferred = $.Deferred();
      promise = deferred.promise();
      result = {
        items: [],
        count: 0
      };
      getAssetsDone = (function(_this) {
        return function(assets, options) {
          if (options == null) {
            options = {};
          }
          if (result.kind === 'Collection') {
            result.items = params.sortoptions ? assets : _this.sortassets(result.assets, assets);
            result.count = assets.length;
            if (options.page) {
              result.next = result.items.length === options.pagesize ? options.page + 1 : void 0;
              result.prev = options.page > 1 ? options.page - 1 : void 0;
            }
          }
          return deferred.resolve(result);
        };
      })(this);
      getAssetsFail = function() {
        return deferred.reject();
      };
      getCollectionDone = (function(_this) {
        return function(collection) {
          if (!collection) {
            return deferred.resolve(result);
          }
          result = collection;
          if (!fetchAssets) {
            return deferred.resolve(result);
          }
          return _this.getAssets(collection, params).done(getAssetsDone).fail(getAssetsFail);
        };
      })(this);
      getCollectionFail = function() {
        return deferred.reject();
      };
      getSearchDone = (function(_this) {
        return function(data, status, xhr) {
          var assets;
          assets = _this.parseData(data);
          result.items = assets.concat(_this.existing || []);
          result.count = assets.length;
          return deferred.resolve(result);
        };
      })(this);
      getSearchFail = function(xhr, statusText, error) {
        return deferred.reject(arguments);
      };
      getLocalSearchDone = (function(_this) {
        return function(data) {
          result.items = data;
          result.count = data.length;
          return deferred.resolve(result);
        };
      })(this);
      getLocalSearchFail = function() {
        return deferred.reject();
      };
      if (ajax === false) {
        this.localSearch(params).done(getLocalSearchDone).fail(getLocalSearchFail);
      } else if (params.path) {
        this.getCollection(params).done(getCollectionDone).fail(getCollectionFail);
      } else {
        this.getSearch(params).done(getSearchDone).fail(getSearchFail);
      }
      return promise;
    },
    localSearch: function(params) {
      var Collection, asset, assets, collection, deferred, id, items, key, kind, path, promise;
      deferred = $.Deferred();
      promise = deferred.promise();
      kind = params.kind;
      if (params.kind) {
        delete params.kind;
      }
      if (params.hasOwnProperty('path')) {
        path = params.path[0];
        if (path !== '/') {
          path = path.replace(/\/$/, "");
        }
        delete params.path;
        Collection = this.get_model('Collection');
        collection = Collection.findByAttribute('path', path);
        assets = (function() {
          var _i, _len, _ref, _results;
          _ref = collection.assets;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            id = _ref[_i];
            if (this.globalExists(id)) {
              _results.push(this.globalFind(id));
            }
          }
          return _results;
        }).call(this);
        if (kind) {
          assets = (function() {
            var _i, _len, _ref, _results;
            _results = [];
            for (_i = 0, _len = assets.length; _i < _len; _i++) {
              asset = assets[_i];
              if (_ref = asset.kind, __indexOf.call(kind, _ref) >= 0) {
                _results.push(asset);
              }
            }
            return _results;
          })();
        }
        for (key in params) {
          if (key === 'text') {
            continue;
          }
          assets = assets.filter(function(item) {
            return item.query(params[key][0], key);
          });
        }
        items = params.text ? assets.filter(function(item) {
          return item.query(params.text[0]);
        }) : assets;
        deferred.resolve(items);
      }
      return promise;
    },
    containedInExcludes: function(params) {
      var colModel, obj, objid;
      if (!params.hasOwnProperty('contained_in')) {
        return params;
      }
      objid = params.contained_in[0];
      colModel = this.get_model('Collection');
      this.existing = colModel.select(function(item) {
        return __indexOf.call(item.assets, objid) >= 0;
      });
      params.excludes = (function() {
        var _i, _len, _ref, _results;
        _ref = this.existing;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          obj = _ref[_i];
          _results.push(obj.id);
        }
        return _results;
      }).call(this);
      return params;
    },
    getSearch: function(params) {
      var jqXHR;
      jqXHR = $.ajax({
        contentType: 'application/json',
        dataType: 'json',
        processData: false,
        headers: {
          'X-Requested-With': 'XMLHttpRequest',
          'NexClient': Nex.client
        },
        type: 'POST',
        data: JSON.stringify(this.containedInExcludes(params)),
        url: this.getSearchUrl()
      });
      jqXHR.always((function(_this) {
        return function() {
          return _this.jqXHR = null;
        };
      })(this));
      jqXHR.fail((function(_this) {
        return function(jqXHR, textStatus, error) {
          if (textStatus === 'abort') {
            return console.log('aborted!');
          }
        };
      })(this));
      if (this.abortable) {
        this.jqXHR = jqXHR;
      }
      return jqXHR;
    },
    getCollection: function(params) {
      var Collection, collection, deferred, exlude, other, path, promise, selector;
      deferred = $.Deferred();
      promise = deferred.promise();
      path = params.path[0];
      if (path !== '/') {
        path = path.replace(/\/$/, "");
      }
      Collection = this.get_model('Collection');
      collection = Collection.findByAttribute('path', path);
      if (!collection) {
        selector = function(item) {
          return item.path === path;
        };
        other = this.filter(selector, exlude = ['Collection', 'Proxy']);
        if (other.length) {
          collection = other[0];
        }
      }
      if (collection) {
        return deferred.resolve(collection);
      } else {
        this.getSearch({
          'path': params.path
        }).done((function(_this) {
          return function(data, status, xhr) {
            delete params.path;
            collection = _this.parseData(data)[0];
            return deferred.resolve(collection);
          };
        })(this));
      }
      return promise;
    },
    getAssets: function(collection, params) {
      var assets, deferred, id, ids, offset, page, pagesize, promise, toFetch, _ref;
      deferred = $.Deferred();
      promise = deferred.promise();
      delete params.path;
      if (collection.kind === 'Collection' && !params.sortoptions) {
        toFetch = collection.assets;
        assets = [];
        page = params.page ? parseInt(params.page) : void 0;
        pagesize = ((_ref = collection.meta.pagesize) != null ? _ref.value : void 0) || 5000;
        if (!Object.keys(params).length) {
          ids = collection.assets;
        }
        if (Object.keys(params).length === 1 && params.hasOwnProperty('kind')) {
          ids = (function() {
            var _i, _len, _ref1, _ref2, _results;
            _ref1 = collection.assets;
            _results = [];
            for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
              id = _ref1[_i];
              if (_ref2 = this.id_to_kind(id), __indexOf.call(params.kind, _ref2) >= 0) {
                _results.push(id);
              }
            }
            return _results;
          }).call(this);
        }
        if (Object.keys(params).length === 1 && params.hasOwnProperty('page')) {
          offset = (page - 1) * (params.pagesize = pagesize);
          ids = collection.assets.slice(offset, pagesize * page);
        }
        if (ids != null ? ids.length : void 0) {
          params.ids = toFetch = (function() {
            var _i, _len, _results;
            _results = [];
            for (_i = 0, _len = ids.length; _i < _len; _i++) {
              id = ids[_i];
              if (!this.globalExists(id)) {
                _results.push(id);
              }
            }
            return _results;
          }).call(this);
          assets = (function() {
            var _i, _len, _results;
            _results = [];
            for (_i = 0, _len = ids.length; _i < _len; _i++) {
              id = ids[_i];
              if (this.globalExists(id)) {
                _results.push(this.globalFind(id));
              }
            }
            return _results;
          }).call(this);
        }
        if (!toFetch.length) {
          return deferred.resolve(assets, {
            page: page,
            pagesize: pagesize
          });
        }
        params.ancestor = collection.id;
        this.getSearch(params).done((function(_this) {
          return function(data, status, xhr) {
            assets = assets.concat(_this.parseData(data));
            return deferred.resolve(assets, {
              page: page,
              pagesize: pagesize
            });
          };
        })(this));
      } else if (collection.kind === 'Collection' && params.sortoptions) {
        params.ancestor = collection.id;
        this.getSearch(params).done((function(_this) {
          return function(data, status, xhr) {
            return deferred.resolve(_this.parseData(data));
          };
        })(this));
      } else {
        deferred.resolve([]);
      }
      return promise;
    },
    sortassets: function(ids, assets) {
      var asset, i, id, orderedlist, _i, _j, _len, _len1;
      orderedlist = [];
      for (_i = 0, _len = ids.length; _i < _len; _i++) {
        id = ids[_i];
        for (i = _j = 0, _len1 = assets.length; _j < _len1; i = ++_j) {
          asset = assets[i];
          if (asset.id === id) {
            orderedlist.push(asset);
            break;
          }
        }
      }
      return orderedlist;
    },
    parseData: function(data) {
      var asset, obj, objs, _i, _len;
      objs = [];
      if (typeof data === 'string') {
        data = JSON.parse(data);
      }
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        obj = data[_i];
        asset = this.create_or_update(obj, {
          ajax: false,
          skipAc: true
        });
        objs.push(asset);
      }
      return objs;
    },
    objListToDict: function(obj_or_list) {
      var elem, key, querydict, value, _i, _j, _len, _len1, _ref;
      querydict = {};
      if (Spine.isArray(obj_or_list)) {
        for (_i = 0, _len = obj_or_list.length; _i < _len; _i++) {
          elem = obj_or_list[_i];
          for (key in elem) {
            value = elem[key];
            querydict[key] || (querydict[key] = []);
            querydict[key].push(value);
          }
        }
      } else {
        for (key in obj_or_list) {
          value = obj_or_list[key];
          querydict[key] = Spine.isArray(value) ? value : [value];
        }
      }
      if (querydict.collection != null) {
        querydict['path'] = querydict.collection;
        delete querydict.collection;
      }
      _ref = ['page', 'pagesize'];
      for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
        key = _ref[_j];
        if (querydict.hasOwnProperty(key)) {
          querydict[key] = querydict[key][0];
        }
      }
      return querydict;
    },
    getSearchUrl: function() {
      if (Nex.data === 'online' && Nex.debug) {
        return "http://" + Nex.tenant + ".imagoapp.com/api/v2/search";
      } else {
        return "/api/v2/search";
      }
    }
  };

  module.exports = Nex.Search;

}).call(this);

//# sourceMappingURL=search.map
