// Generated by CoffeeScript 1.6.3
(function() {
  var Nex,
    _this = this;

  Nex = this.Nex || require('nex');

  Nex.Gallery = {
    renderGallery: function() {},
    cur: 0,
    next: function() {
      if (!(_this.cur < (_this.manager.controllers.length - 1))) {
        return;
      }
      _this.cur++;
      return _this.manager.controllers[_this.cur].active();
    },
    prev: function() {
      if (!(_this.cur > 0)) {
        return;
      }
      _this.cur--;
      return _this.manager.controllers[_this.cur].active();
    }
  };

  module.exports = Nex.Gallery;

}).call(this);
