// Generated by CoffeeScript 1.6.3
(function() {
  var Nex;

  Nex = this.Nex || require('nex');

  Nex.SimpleGallery = {
    cur: 0,
    next: function() {
      if (!(this.cur < (this.manager.controllers.length - 1))) {
        return;
      }
      this.cur++;
      return this.manager.controllers[this.cur].active();
    },
    prev: function() {
      if (!(this.cur > 0)) {
        return;
      }
      this.cur--;
      return this.manager.controllers[this.cur].active();
    }
  };

  module.exports = Nex.SimpleGallery;

}).call(this);

/*
//@ sourceMappingURL=simplegallery.map
*/
