// Generated by CoffeeScript 1.6.3
(function() {
  var Nex, Slide,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Nex = this.Nex || require('nex');

  Nex.Slider = (function(_super) {
    __extends(Slider, _super);

    Slider.include(Nex.Panel);

    Slider.prototype.logPrefix = '(App) Nex.Slider: ';

    Slider.prototype.className = 'nexslider';

    Slider.prototype.events = {
      'tap .next': 'next',
      'tap .prev': 'prev',
      'keyup': 'onKeyup'
    };

    Slider.prototype.defaults = {
      animation: 'fade',
      easing: 'swing',
      sizemode: 'fit',
      current: 0,
      autoplay: true,
      enablekeys: true,
      sizemode: 'fit'
    };

    function Slider() {
      this.prev = __bind(this.prev, this);
      this.next = __bind(this.next, this);
      this.render = __bind(this.render, this);
      this.onKeyup = __bind(this.onKeyup, this);
      var key, value, _ref;
      _ref = this.defaults;
      for (key in _ref) {
        value = _ref[key];
        this[key] = value;
      }
      Slider.__super__.constructor.apply(this, arguments);
      this.el.addClass(this.animation);
      this.manager = new Spine.Manager;
      this.bind('ready', this.render);
      if (this.enablekeys) {
        document.addEventListener('keydown', this.onKeyup);
      }
      if (this["class"]) {
        this.el.addClass(this["class"]);
      }
      this.html('<div class="prev"></div><div class="next"></div>');
      if (this.path) {
        this.getData(this.path);
      } else {
        this.active(this.getData);
      }
    }

    Slider.prototype.onKeyup = function(e) {
      if (!(this.enablekeys && this.isActive())) {
        return;
      }
      switch (e.keyCode) {
        case 37:
          return this.prev();
        case 39:
          return this.next();
      }
    };

    Slider.prototype.render = function(result) {
      var asset, i, _i, _len, _ref;
      this.activate();
      _ref = result.items;
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        asset = _ref[i];
        this.add(new Slide({
          asset: asset,
          sizemode: this.sizemode
        }));
      }
      return this.manager.controllers[this.current].active();
    };

    Slider.prototype.clear = function() {
      var cont, _i, _len, _ref, _results;
      _ref = this.controllers;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        cont = _ref[_i];
        _results.push(this.controllers[0].release());
      }
      return _results;
    };

    Slider.prototype.add = function(controller) {
      this.manager.add(controller);
      return this.append(controller);
    };

    Slider.prototype.next = function() {
      if (this.current < (this.manager.controllers.length - 1)) {
        this.current++;
      } else {
        this.current = 0;
      }
      return this.manager.controllers[this.current].active();
    };

    Slider.prototype.prev = function() {
      if (this.current > 0) {
        this.current--;
      } else {
        this.current = this.manager.controllers.length - 1;
      }
      return this.manager.controllers[this.current].active();
    };

    return Slider;

  })(Spine.Controller);

  module.exports = Nex.Slider;

  Slide = (function(_super) {
    __extends(Slide, _super);

    Slide.include(Nex.Panel);

    Slide.prototype.logPrefix = '(App) Slide: ';

    Slide.prototype.className = 'slide';

    function Slide() {
      var assets;
      Slide.__super__.constructor.apply(this, arguments);
      this.controllers = [];
      assets = this.asset.items || [this.asset];
      this.bind('ready', this.render);
      if (this.asset.assets) {
        this.getData(this.asset.path);
      } else {
        this.render();
      }
    }

    Slide.prototype.render = function(result) {
      var asset, assets, html, i, _i, _len, _ref, _results;
      assets = (result != null ? result.items : void 0) || [this.asset];
      if (!((assets != null ? assets.length : void 0) > 0)) {
        return;
      }
      this.el.addClass("_" + assets.length);
      _results = [];
      for (i = _i = 0, _len = assets.length; _i < _len; i = ++_i) {
        asset = assets[i];
        this.add(this["asset" + i] = new Nex.Widgets[asset === 'Image' || asset === 'Video' ? asset.kind : 'Image']({
          src: asset.serving_url,
          align: ((_ref = asset.meta.crop) != null ? _ref.value : void 0) || 'center center',
          resolution: asset.resolution,
          uuid: asset.id,
          formats: asset.formats,
          sizemode: this.sizemode,
          lazy: false
        }));
        html = asset.getMeta('html', '');
        if (html) {
          _results.push(this.append(html));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Slide.prototype.add = function(controller) {
      this.controllers.push(controller);
      return this.append(controller);
    };

    Slide.prototype.clear = function() {
      var cont, _i, _len, _ref;
      _ref = this.controllers;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        cont = _ref[_i];
        this.controllers[0].release();
      }
      this.controllers = [];
      return this.html('');
    };

    return Slide;

  })(Spine.Controller);

}).call(this);

/*
//@ sourceMappingURL=slider.map
*/
