// Generated by CoffeeScript 1.8.0
(function() {
  var Nex, Tab,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  require("./panel");

  Nex = this.Nex || require('nex');

  Nex.Widgets.Tabs = (function(_super) {
    __extends(Tabs, _super);

    Tabs.include(Nex.Panel);

    Tabs.prototype.logPrefix = '(App) Tabs: ';

    Tabs.prototype.className = 'tabs';

    Tabs.prototype.elements = {
      'nav': 'navigation'
    };

    Tabs.prototype.events = {
      'tap nav a': 'onClick'
    };

    function Tabs() {
      Tabs.__super__.constructor.apply(this, arguments);
      this.html("<nav></nav>");
      this.controllers = [];
      this.bind('ready', this.render);
      if (this.path) {
        this.getData(this.path);
      } else {
        this.active(this.getData);
      }
    }

    Tabs.prototype.render = function(result) {
      var asset, col, i, _i, _j, _len, _len1, _ref;
      for (_i = 0, _len = result.length; _i < _len; _i++) {
        col = result[_i];
        _ref = col.items;
        for (i = _j = 0, _len1 = _ref.length; _j < _len1; i = ++_j) {
          asset = _ref[i];
          this.navigation.append("<a href='#tab" + i + "'>" + (asset.getMeta('title', asset.getMeta('headline'))) + "</a>");
          this.add(new Tab({
            i: i,
            asset: asset
          }));
        }
      }
      this.links = this.$('nav a');
      this.links.eq(0).addClass('active');
      this.content = this.$('article');
      return this.content.eq(0).addClass('active');
    };

    Tabs.prototype.add = function(controller) {
      this.controllers.push(controller);
      return this.append(controller);
    };

    Tabs.prototype.onClick = function(e) {
      var target;
      e.preventDefault();
      this.links.removeClass('active');
      this.content.removeClass('active');
      target = $(e.target);
      target.addClass('active');
      return this.content.filter(target.attr('href')).addClass('active');
    };

    Tabs.prototype.clear = function() {
      var controller, _i, _len, _ref, _results;
      _ref = this.controllers;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        controller = _ref[_i];
        _results.push(controller.release());
      }
      return _results;
    };

    Tabs.prototype.deactivate = function() {
      this.clear();
      return Tabs.__super__.deactivate.apply(this, arguments);
    };

    return Tabs;

  })(Spine.Controller);

  module.exports = Nex.Widgets.Tabs;

  Tab = (function(_super) {
    __extends(Tab, _super);

    Tab.include(Nex.Panel);

    Tab.prototype.logPrefix = '(App) Tab: ';

    Tab.prototype.tag = 'article';

    function Tab() {
      Tab.__super__.constructor.apply(this, arguments);
      this.el.attr('id', "tab" + this.i);
      this.controllers = [];
      if (this.asset.kind === 'Collection') {
        this.bind('ready', this.render);
        this.getData(this.asset.path);
      } else {
        this.render([this.asset]);
      }
    }

    Tab.prototype.render = function(result) {
      var asset, item, _i, _j, _len, _len1, _ref, _results;
      _results = [];
      for (_i = 0, _len = result.length; _i < _len; _i++) {
        asset = result[_i];
        this.html(asset.getMeta('text', asset.getMeta('html')));
        this.appendWidget(asset);
        if (asset.kind === 'Collection') {
          _ref = asset.items;
          for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
            item = _ref[_j];
            this.appendWidget(item);
          }
        }
        break;
      }
      return _results;
    };

    Tab.prototype.appendWidget = function(asset) {
      var el;
      if (!(asset && (el = this.$("." + asset.normname)[0]))) {
        return;
      }
      return this.controllers.push(new Nex.Widgets[asset.kind === 'Collection' ? 'Slider' : asset.kind]({
        el: el,
        src: asset.serving_url,
        align: asset.getMeta('crop', 'center center'),
        resolution: asset.resolution,
        uuid: asset.id,
        formats: asset.formats,
        path: asset.path,
        lazy: false,
        animation: asset.getMeta('animation', 'scalerotate'),
        sizemode: asset.getMeta('sizemode', ['crop'])[0]
      }));
    };

    Tab.prototype.deactivate = function() {
      this.clear();
      return Tab.__super__.deactivate.apply(this, arguments);
    };

    Tab.prototype.clear = function() {
      var cont, _i, _len, _ref;
      _ref = this.controllers;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        cont = _ref[_i];
        cont.release();
      }
      return this.controllers = [];
    };

    return Tab;

  })(Spine.Controller);

}).call(this);
