// Generated by CoffeeScript 1.6.3
(function() {
  var Controls, Nex, VideoElement,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Nex = this.Nex || require('nex');

  Nex.Widgets.Video = (function(_super) {
    __extends(Video, _super);

    Video.prototype.className = 'imagovideo';

    Video.prototype.defaults = {
      autobuffer: null,
      autoplay: false,
      controls: true,
      preload: 'none',
      size: 'hd',
      align: 'left top',
      sizemode: 'fit',
      lazy: true
    };

    Video.prototype.events = {
      'mousemove': 'activateControls',
      'keydown': 'activateControls',
      'DOMMouseScroll': 'activateControls',
      'mousewheel': 'activateControls',
      'mousedown': 'activateControls',
      'tap .playbig': 'togglePlay'
    };

    function Video() {
      this.togglePlay = __bind(this.togglePlay, this);
      this.stop = __bind(this.stop, this);
      this.pause = __bind(this.pause, this);
      this.activateControls = __bind(this.activateControls, this);
      this.resize = __bind(this.resize, this);
      var key, r, value, w, _ref;
      _ref = this.defaults;
      for (key in _ref) {
        value = _ref[key];
        this[key] = value;
      }
      Video.__super__.constructor.apply(this, arguments);
      this.logPrefix = '(App) Video: ';
      this.id = Nex.Utils.uuid();
      this.append(this.videoEl = new VideoElement({
        player: this
      }));
      this.video = this.videoEl.video;
      this.el.addClass("" + (this["class"] || '') + " " + this.size + " " + this.align + " " + this.sizemode);
      this.append(this.playbig = $('<div class="spin"></div><div class="spin2"></div><a class="playbig icon-play" />'));
      this.on('videoready', function() {
        if (this.controls) {
          return this.append(this.controlBar = new Controls({
            player: this
          }));
        }
      });
      if (this.width) {
        this.el.width(this.width);
      }
      if (this.height) {
        this.el.height(this.height);
      }
      w = $(window).on("resize." + this.id, this.resize);
      if (typeof this.resolution === 'string') {
        r = this.resolution.split('x');
        this.resolution = {
          width: r[0],
          height: r[1]
        };
      }
      this.delay(function() {
        this.resize();
        this.setupPosterFrame();
        return this.resize();
      }, 330);
      this;
    }

    Video.prototype.resize = function() {
      var assetRatio, height, s, width, wrapperRatio;
      assetRatio = this.resolution.width / this.resolution.height;
      if (this.sizemode === 'crop') {
        width = this.width || this.el.width();
        height = this.height || this.el.height();
        wrapperRatio = width / height;
        if (assetRatio < wrapperRatio) {
          if (Nex.Utils.isiOS()) {
            s = {
              width: '100%',
              height: '100%'
            };
            if (this.align === 'center center') {
              s.top = '0';
              s.left = '0';
            }
          } else {
            s = {
              width: '100%',
              height: 'auto'
            };
            if (this.align === 'center center') {
              s.top = '50%';
              s.left = 'auto';
              s.marginTop = "-" + (width / assetRatio / 2) + "px";
              s.marginLeft = "0px";
            }
          }
          this.videoEl.el.css(s);
          return this.el.css({
            backgroundSize: '100% auto',
            backgroundPosition: this.align
          });
        } else {
          if (Nex.Utils.isiOS()) {
            s = {
              width: '100%',
              height: '100%'
            };
            if (this.align === 'center center') {
              s.top = '0';
              s.left = '0';
            }
          } else {
            s = {
              width: 'auto',
              height: '100%'
            };
            if (this.align === 'center center') {
              s.top = 'auto';
              s.left = '50%';
              s.marginTop = "0px";
              s.marginLeft = "-" + (height * assetRatio / 2) + "px";
            }
          }
          this.videoEl.el.css(s);
          return this.el.css({
            backgroundSize: 'auto 100%',
            backgroundPosition: this.align
          });
        }
      } else {
        width = this.width || this.el.parent().width();
        height = this.height || this.el.parent().height();
        wrapperRatio = width / height;
        if (assetRatio > wrapperRatio) {
          this.videoEl.el.css({
            width: '100%',
            height: 'auto'
          });
          return this.el.css({
            backgroundSize: '100% auto',
            backgroundPosition: this.align,
            width: "" + width + "px",
            height: "" + (width / assetRatio) + "px"
          });
        } else {
          this.videoEl.el.css({
            width: 'auto',
            height: '100%'
          });
          return this.el.css({
            backgroundSize: 'auto 100%',
            backgroundPosition: this.align,
            width: "" + (height * assetRatio) + "px",
            height: "" + height + "px"
          });
        }
      }
    };

    Video.prototype.setupPosterFrame = function() {
      var css, dpr, height, width;
      if (!($.inviewport(this.el, {
        threshold: 0
      })) && this.lazy) {
        return;
      }
      dpr = this.hires ? Math.ceil(window.devicePixelRatio) || 1 : 1;
      width = this.width || this.el.width();
      height = this.height || this.el.height();
      this.serving_url = this.src;
      this.serving_url += "=s" + (Math.ceil(Math.min(Math.max(width, height) * dpr, 1600)));
      css = {
        backgroundImage: "url(" + this.serving_url + ")",
        backgroundPosition: this.align
      };
      css.backgroundSize = "auto 100%";
      if (Number(this.width)) {
        css.width = "" + width + "px";
      }
      if (Number(this.height)) {
        css.height = "" + height + "px";
      }
      return this.el.css(css);
    };

    Video.prototype.activateControls = function() {
      if (!this.controlBar) {
        return;
      }
      return this.controlBar.activate();
    };

    Video.prototype.play = function() {
      return this.delay(this.videoEl.play, 500);
    };

    Video.prototype.pause = function() {
      return this.videoEl.pause();
    };

    Video.prototype.stop = function() {
      return this.pause();
    };

    Video.prototype.togglePlay = function() {
      return this.videoEl.togglePlay();
    };

    return Video;

  })(Spine.Controller);

  module.exports = Nex.Widgets.Video;

  VideoElement = (function(_super) {
    __extends(VideoElement, _super);

    VideoElement.prototype.tag = 'video';

    VideoElement.prototype.events = {
      'click': 'click',
      'dblclick': 'dblclick',
      'error': 'onerror',
      'loadstart': 'onloadstart',
      'loadeddata': 'onloadeddata',
      'progress': 'onprogress',
      'canplay': 'oncanplay',
      'durationchange': 'ondurationchange',
      'timeupdate': 'ontimeupdate',
      'pause': 'onpause',
      'play': 'onplay',
      'ended': 'onended',
      'volumechange': 'onvolumechange'
    };

    function VideoElement() {
      this.onended = __bind(this.onended, this);
      this.onplay = __bind(this.onplay, this);
      this.onpause = __bind(this.onpause, this);
      this.ondurationchange = __bind(this.ondurationchange, this);
      this.oncanplay = __bind(this.oncanplay, this);
      this.onloadstart = __bind(this.onloadstart, this);
      this.onloadeddata = __bind(this.onloadeddata, this);
      this.onprogress = __bind(this.onprogress, this);
      this.onerror = __bind(this.onerror, this);
      this.dblclick = __bind(this.dblclick, this);
      this.click = __bind(this.click, this);
      this.play = __bind(this.play, this);
      VideoElement.__super__.constructor.apply(this, arguments);
      this.logPrefix = '(App) VideoElement: ';
      this.codecs = ['mp4', 'webm'];
      this.video = this.el[0];
      this.el.attr({
        autoplay: this.player.autoplay,
        preload: this.player.preload,
        autobuffer: this.player.autobuffer,
        'x-webkit-airplay': 'allow',
        webkitAllowFullscreen: 'true'
      });
      this.loadSources();
    }

    VideoElement.prototype.loadSources = function() {
      var codec, format, i, src, srcEl, _i, _len, _ref, _results;
      if (!this.player.uuid) {
        return;
      }
      codec = this.detectCodec();
      this.player.formats.sort(function(a, b) {
        return b.height - a.height;
      });
      this.el.empty();
      _ref = this.player.formats;
      _results = [];
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        format = _ref[i];
        if (codec !== format.codec) {
          continue;
        }
        src = "http://" + Nex.tenant + ".imagoapp.com/assets/api/play_redirect?uuid=" + this.player.uuid + "&codec=" + format.codec + "&quality=hd&max_size=" + format.size;
        srcEl = $('<source />', {
          src: src,
          'data-size': format.size,
          'data-codec': format.codec,
          type: "video/" + codec
        });
        _results.push(this.el.append(srcEl));
      }
      return _results;
    };

    VideoElement.prototype.detectCodec = function() {
      var codecs, key, tag, value;
      tag = document.createElement('video');
      if (!tag.canPlayType) {
        return;
      }
      codecs = {
        mp4: 'video/mp4; codecs="mp4v.20.8"',
        mp4: 'video/mp4; codecs="avc1.42E01E"',
        mp4: 'video/mp4; codecs="avc1.42E01E, mp4a.40.2"',
        webm: 'video/webm; codecs="vp8, vorbis"',
        ogg: 'video/ogg; codecs="theora"'
      };
      for (key in codecs) {
        value = codecs[key];
        if (tag.canPlayType(value)) {
          return key;
        }
      }
    };

    VideoElement.prototype.setSize = function(size) {
      var poster, srcs, time,
        _this = this;
      time = this.getCurrentTime();
      srcs = this.el.children('source');
      if (!(srcs.length > 1)) {
        return;
      }
      poster = this.player.el.css('backgroundImage');
      this.player.el.css('backgroundImage', '');
      this.el.one('loadeddata', function() {
        _this.seek(time);
        _this.el.css('display', 'block');
        _this.player.el.css('backgroundImage', poster);
        return _this.play();
      });
      this.pause();
      this.el.css('display', 'none');
      this.el.attr('src', srcs[(size === "hd" ? 0 : srcs.length - 1)].src);
      return this.video.load();
    };

    VideoElement.prototype.play = function() {
      return this.video.play();
    };

    VideoElement.prototype.pause = function() {
      return this.video.pause();
    };

    VideoElement.prototype.seek = function(offset) {
      var state;
      state = this.state;
      this.pause();
      this.setCurrentTime(offset);
      if (state === 'playing') {
        return this.play();
      }
    };

    VideoElement.prototype.setCurrentTime = function(offset) {
      return this.video.currentTime(offset);
    };

    VideoElement.prototype.togglePlay = function() {
      if (this.state === 'playing') {
        return this.pause();
      } else {
        return this.play();
      }
    };

    VideoElement.prototype.getDuration = function() {
      return this.video.duration;
    };

    VideoElement.prototype.getStartTime = function() {
      return this.video.startTime || 0;
    };

    VideoElement.prototype.getEndTime = function() {
      if (this.video.duration === Infinity && this.video.buffered) {
        return this.video.buffered.end(this.video.buffered.length - 1);
      } else {
        return (this.video.startTime || 0) + this.video.duration;
      }
    };

    VideoElement.prototype.getCurrentTime = function() {
      var e;
      try {
        return this.video.currentTime;
      } catch (_error) {
        e = _error;
        return 0;
      }
    };

    VideoElement.prototype.setCurrentTime = function(val) {
      return this.video.currentTime = val;
    };

    VideoElement.prototype.getVolume = function() {
      return this.video.volume;
    };

    VideoElement.prototype.setVolume = function(val) {
      return this.video.volume = val;
    };

    VideoElement.prototype.enterFullScreen = function(e) {
      return this.video.webkitEnterFullScreen();
    };

    VideoElement.prototype.exitFullScreen = function() {};

    VideoElement.prototype.click = function() {
      return this.togglePlay();
    };

    VideoElement.prototype.dblclick = function() {};

    VideoElement.prototype.onerror = function(e) {
      return this.log('onerror', e);
    };

    VideoElement.prototype.onprogress = function() {
      return this.player.el.addClass('loading');
    };

    VideoElement.prototype.onloadeddata = function() {
      this.player.el.removeClass('loading');
      return this.player.trigger('videoready');
    };

    VideoElement.prototype.onloadstart = function() {};

    VideoElement.prototype.oncanplay = function() {
      return this.player.el.removeClass('loading');
    };

    VideoElement.prototype.ondurationchange = function() {};

    VideoElement.prototype.ontimeupdate = function(e) {
      return this.trigger('timeupdate', e);
    };

    VideoElement.prototype.onpause = function() {
      this.state = 'paused';
      return this.player.el.removeClass('playing');
    };

    VideoElement.prototype.onplay = function() {
      this.state = 'playing';
      this.player.el.addClass('playing');
      return this.player.el.removeClass('loading');
    };

    VideoElement.prototype.onended = function() {
      return this.state = 'stopped';
    };

    VideoElement.prototype.onvolumechange = function(e) {
      return this.trigger('timeupdate', e);
    };

    return VideoElement;

  })(Spine.Controller);

  Controls = (function(_super) {
    __extends(Controls, _super);

    Controls.prototype.className = 'controls active';

    Controls.prototype.elements = {
      '.time': 'time',
      '.seek': 'seek',
      '.volume input': 'volume'
    };

    Controls.prototype.events = {
      'click .play': 'play',
      'click .pause': 'pause',
      'change .seek': 'onSeek',
      'click .size': 'toggleSize',
      'change .volume input': 'onVolumeChnage',
      'click .fullscreen': 'onEnterFullScreen'
    };

    function Controls() {
      this.doDelayed = __bind(this.doDelayed, this);
      this.onEnterFullScreen = __bind(this.onEnterFullScreen, this);
      this.onVolumeChnage = __bind(this.onVolumeChnage, this);
      this.toggleSize = __bind(this.toggleSize, this);
      this.onSeek = __bind(this.onSeek, this);
      this.ontimeupdate = __bind(this.ontimeupdate, this);
      Controls.__super__.constructor.apply(this, arguments);
      this.logPrefix = '(App) Controls: ';
      this.html('<a class="play icon-play"></a><a class="pause icon-pause"></a><span class="time">00:00</span><span class="seekbar"><input type="range" value="0" class="seek"/></span><a class="size">hd</a><span class="volume"><span class="icon-volume-up"></span><input type="range" value="100"/><span class="icon-volume-down"></span></span><a class="fullscreen icon-resize-full"></a><a class="screen icon-resize-small"></a>');
      this.player.videoEl.on('timeupdate', this.ontimeupdate);
      this.activate();
    }

    Controls.prototype.play = function(e) {
      return this.player.videoEl.play();
    };

    Controls.prototype.pause = function(e) {
      return this.player.videoEl.pause();
    };

    Controls.prototype.ontimeupdate = function(e) {
      this.time.html(this.formatTime(this.player.videoEl.getCurrentTime()));
      return this.seek.val(this.player.videoEl.getCurrentTime() / this.player.videoEl.getEndTime() * 100);
    };

    Controls.prototype.pad = function(num) {
      if (num < 10) {
        return "0" + num;
      }
      return num;
    };

    Controls.prototype.formatTime = function(sec) {
      var hours, minutes, result, seconds;
      result = [];
      minutes = Math.floor(sec / 60);
      hours = Math.floor(sec / 3600);
      seconds = (sec === 0 ? 0 : sec % 60);
      seconds = Math.round(seconds);
      if (hours > 0) {
        result.push(this.pad(hours));
      }
      result.push(this.pad(minutes));
      result.push(this.pad(seconds));
      return result.join(":");
    };

    Controls.prototype.onSeek = function(e) {
      var value;
      value = this.player.videoEl.getEndTime() / 100 * $(e.target).val();
      return this.player.videoEl.seek(value);
    };

    Controls.prototype.toggleSize = function(e) {
      var size;
      if (this.player.size === 'hd') {
        size = 'sd';
      } else {
        size = 'hd';
      }
      this.player.el.addClass(size).removeClass(this.player.size);
      this.player.size = size;
      return this.player.videoEl.setSize(size);
    };

    Controls.prototype.onVolumeChnage = function(e) {
      var value;
      value = $(e.target).val() / 100;
      return this.player.videoEl.setVolume(value);
    };

    Controls.prototype.onEnterFullScreen = function(e) {
      if (!screenfull.enabled) {
        return;
      }
      return screenfull.request(this.player.video);
    };

    Controls.prototype.doDelayed = function(func, sec) {
      if (this.idleTimer) {
        clearTimeout(this.idleTimer);
      }
      return this.idleTimer = this.delay(func, sec || 2000);
    };

    Controls.prototype.activate = function(e) {
      this.doDelayed(this.deactivate);
      return this.el.addClass('active');
    };

    Controls.prototype.deactivate = function() {
      return this.el.removeClass('active');
    };

    return Controls;

  })(Spine.Controller);

}).call(this);

/*
//@ sourceMappingURL=video.map
*/
