// Generated by CoffeeScript 1.6.3
(function() {
  require('./jquery.viewport');

  Nex.Widgets = {
    Image: require("./image"),
    Video: require("./video")
  };

  module.exports = Nex.Widgets;

}).call(this);
